<?php
/**
 * MUPolls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUPolls
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing option translations.
 *
 * This is the concrete translation class for option entities.
 *
 * @ORM\Entity(repositoryClass="MUPolls_Entity_Repository_OptionTranslation")
 * @ORM\Table(name="mupolls_option_translation",
 *     indexes={
 *         @ORM\Index(name="translations_lookup_idx", columns={
 *             "locale", "object_class", "foreign_key"
 *         })
 *     }
 * )
 */
class MUPolls_Entity_OptionTranslation extends MUPolls_Entity_Base_AbstractOptionTranslation
{
    // feel free to add your own methods here
}
