<?php
/**
 * MUPolls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUPolls
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

/**
 * This handler class handles the page events of the Form called by the mUPolls_poll_edit() function.
 * It aims on the poll object type.
 */
class MUPolls_Form_Handler_Poll_Edit extends MUPolls_Form_Handler_Poll_Base_AbstractEdit
{
    // feel free to extend the base handler class here
}
