<?php
/**
 * MUPolls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUPolls
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

use Gedmo\Translatable\Entity\AbstractTranslation;

/**
 * Entity extension domain class storing option translations.
 *
 * This is the base translation class for option entities.
 */
abstract class MUPolls_Entity_Base_AbstractOptionTranslation extends AbstractTranslation
{
}
