<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\PollsModule\DependencyInjection;

use MU\PollsModule\DependencyInjection\Base\AbstractMUPollsExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class MUPollsExtension extends AbstractMUPollsExtension
{
    // custom enhancements can go here
}
