<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\PollsModule\Form\Handler\Option;

use MU\PollsModule\Form\Handler\Option\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of the Form called by the mUPollsModule_option_edit() function.
 * It aims on the option object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
