<?php
/**
 * MUPolls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUPolls
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

/**
 * Configuration handler implementation class.
 */
class MUPolls_Form_Handler_Admin_Config extends MUPolls_Form_Handler_Admin_Base_AbstractConfig
{
    /**
     * Initialize form handler.
     *
     * This method takes care of all necessary initialisation of our data and form states.
     *
     * @param Zikula_Form_View $view The form view instance
     *
     * @return boolean False in case of initialization errors, otherwise true
     */
    public function initialize(Zikula_Form_View $view)
    {
        // permission check
        if (!SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            return $view->registerError(LogUtil::registerPermissionError());
        }

        // retrieve module vars
        $modVars = $this->getVars();

        // initialise list entries for the 'kind of voting' setting
        
        $modVars['kindOfVotingItems'] = array(array(array('value' => 'session', 'text' => 'Session'))
        );

        // assign all module vars
        $this->view->assign('config', $modVars);

        // everything okay, no initialization errors occured
        return true;
    }
}
