<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\PollsModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use MU\PollsModule\Entity\OptionEntity;

/**
 * Event base class for filtering option processing.
 */
class AbstractFilterOptionEvent extends Event
{
    /**
     * @var OptionEntity Reference to treated entity instance.
     */
    protected $option;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterOptionEvent constructor.
     *
     * @param OptionEntity $option Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(OptionEntity $option, $entityChangeSet = [])
    {
        $this->option = $option;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return OptionEntity
     */
    public function getOption()
    {
        return $this->option;
    }

    /**
     * Returns the change set.
     *
     * @return array
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
