<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\PollsModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use MU\PollsModule\Entity\VoteEntity;

/**
 * Event base class for filtering vote processing.
 */
class AbstractFilterVoteEvent extends Event
{
    /**
     * @var VoteEntity Reference to treated entity instance.
     */
    protected $vote;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterVoteEvent constructor.
     *
     * @param VoteEntity $vote Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(VoteEntity $vote, array $entityChangeSet = [])
    {
        $this->vote = $vote;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return VoteEntity
     */
    public function getVote()
    {
        return $this->vote;
    }

    /**
     * Returns the change set.
     *
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
