<?php
/**
 * MUPolls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUPolls
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * This is the Admin api helper class.
 */
class MUPolls_Api_Base_Admin extends Zikula_AbstractApi
{
    /**
     * Returns available admin panel links.
     *
     * @return array Array of admin links.
     */
    public function getLinks()
    {
        $links = array();

        $controllerHelper = new MUPolls_Util_Controller($this->serviceManager);
        $utilArgs = array('api' => 'admin', 'action' => 'getLinks');
        $allowedObjectTypes = $controllerHelper->getObjectTypes('api', $utilArgs);

        $currentType = $this->request->query->filter('type', 'poll', FILTER_SANITIZE_STRING);
        $currentLegacyType = $this->request->query->filter('lct', 'user', FILTER_SANITIZE_STRING);
        $permLevel = in_array('admin', array($currentType, $currentLegacyType)) ? ACCESS_ADMIN : ACCESS_READ;

        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_READ)) {
            $links[] = array(
                'url' => ModUtil::url($this->name, 'user', 'main'),
                 'text' => $this->__('Frontend'),
                 'title' => $this->__('Switch to user area.'),
                 'class' => 'z-icon-es-home'
             );
        }
        
        if (in_array('option', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Option:', '::', $permLevel)) {
            $links[] = array(
                'url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'option')),
                 'text' => $this->__('Options'),
                 'title' => $this->__('Option list')
             );
        }
        if (in_array('poll', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Poll:', '::', $permLevel)) {
            $links[] = array(
                'url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'poll')),
                 'text' => $this->__('Polls'),
                 'title' => $this->__('Poll list')
             );
        }
        if (in_array('vote', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Vote:', '::', $permLevel)) {
            $links[] = array(
                'url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'vote')),
                 'text' => $this->__('Votes'),
                 'title' => $this->__('Vote list')
             );
        }
        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            $links[] = array(
                'url' => ModUtil::url($this->name, 'admin', 'config'),
                 'text' => $this->__('Configuration'),
                 'title' => $this->__('Manage settings for this application')
             );
        }

        return $links;
    }
}
