<?php
/**
 * MUPolls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUPolls
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

/**
 * The mupollsObjectState modifier displays the name of a given object's workflow state.
 * Examples:
 *    {$item.workflowState|mupollsObjectState}       {* with visual feedback *}
 *    {$item.workflowState|mupollsObjectState:false} {* no ui feedback *}
 *
 * @param string  $state      Name of given workflow state
 * @param boolean $uiFeedback Whether the output should include some visual feedback about the state
 *
 * @return string Enriched and translated workflow state ready for display
 */
function smarty_modifier_mupollsObjectState($state = 'initial', $uiFeedback = true)
{
    $serviceManager = ServiceUtil::getManager();
    $workflowHelper = new MUPolls_Util_Workflow($serviceManager);

    $stateInfo = $workflowHelper->getStateInfo($state);

    $result = $stateInfo['text'];
    if ($uiFeedback === true) {
        $result = '<img src="' . System::getBaseUrl() . 'images/icons/extrasmall/' . $stateInfo['ui'] . 'led.png" width="16" height="16" alt="' . $result . '" />&nbsp;&nbsp;' . $result;
    }

    return $result;
}
