<?php
/**
 * MUPolls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUPolls
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de) at Sun Oct 02 13:51:53 CEST 2016.
 */

/**
 * Version information base class.
 */
abstract class MUPolls_Base_AbstractVersion extends Zikula_AbstractVersion
{
    /**
     * Retrieves meta data information for this application.
     *
     * @return array List of meta data
     */
    public function getMetaData()
    {
        $meta = array();
        // the current module version
        $meta['version']              = '0.5.0';
        // the displayed name of the module
        $meta['displayname']          = $this->__('M u polls');
        // the module description
        $meta['description']          = $this->__('M u polls module generated by ModuleStudio 0.7.0.');
        //! url version of name, should be in lowercase without space
        $meta['url']                  = $this->__('mupolls');
        // core requirement
        $meta['core_min']             = '1.3.5'; // requires minimum 1.3.5
        $meta['core_max']             = '1.3.99'; // not ready for 1.4.0 yet

        // define special capabilities of this module
        $meta['capabilities'] = array(
              HookUtil::SUBSCRIBER_CAPABLE => array('enabled' => true)
/*,
              HookUtil::PROVIDER_CAPABLE => array('enabled' => true), // TODO: see #15
*/
        );

        // permission schema
        $meta['securityschema'] = array(
            'MUPolls::' => '::',
            'MUPolls::Ajax' => '::',
            'MUPolls:ItemListBlock:' => 'Block title::',
            'MUPolls:Option:' => 'Option ID::',
            'MUPolls:Poll:' => 'Poll ID::',
            'MUPolls:Vote:' => 'Vote ID::',
        );


        return $meta;
    }

    /**
     * Defines hook subscriber bundles.
     */
    protected function setupHookBundles()
    {
        $bundle = new Zikula_HookManager_SubscriberBundle('MUPolls', 'subscriber.mupolls..ui_hooks.options', 'ui_hooks', $this->__('mupolls. Options Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'mupolls.ui_hooks.options.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'mupolls.ui_hooks.options.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'mupolls.ui_hooks.options.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'mupolls.ui_hooks.options.validate_edit');
        // Validate input from an ui delete form.
        $bundle->addEvent('validate_delete', 'mupolls.ui_hooks.options.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'mupolls.ui_hooks.options.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'mupolls.ui_hooks.options.process_delete');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new Zikula_HookManager_SubscriberBundle('MUPolls', 'subscriber.mupolls..filter_hooks.options', 'filter_hooks', $this->__('mupolls. Options Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'mupolls.filter_hooks.options.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new Zikula_HookManager_SubscriberBundle('MUPolls', 'subscriber.mupolls..ui_hooks.polls', 'ui_hooks', $this->__('mupolls. Polls Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'mupolls.ui_hooks.polls.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'mupolls.ui_hooks.polls.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'mupolls.ui_hooks.polls.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'mupolls.ui_hooks.polls.validate_edit');
        // Validate input from an ui delete form.
        $bundle->addEvent('validate_delete', 'mupolls.ui_hooks.polls.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'mupolls.ui_hooks.polls.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'mupolls.ui_hooks.polls.process_delete');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new Zikula_HookManager_SubscriberBundle('MUPolls', 'subscriber.mupolls..filter_hooks.polls', 'filter_hooks', $this->__('mupolls. Polls Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'mupolls.filter_hooks.polls.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new Zikula_HookManager_SubscriberBundle('MUPolls', 'subscriber.mupolls..ui_hooks.votes', 'ui_hooks', $this->__('mupolls. Votes Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'mupolls.ui_hooks.votes.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'mupolls.ui_hooks.votes.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'mupolls.ui_hooks.votes.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'mupolls.ui_hooks.votes.validate_edit');
        // Validate input from an ui delete form.
        $bundle->addEvent('validate_delete', 'mupolls.ui_hooks.votes.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'mupolls.ui_hooks.votes.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'mupolls.ui_hooks.votes.process_delete');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new Zikula_HookManager_SubscriberBundle('MUPolls', 'subscriber.mupolls..filter_hooks.votes', 'filter_hooks', $this->__('mupolls. Votes Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'mupolls.filter_hooks.votes.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        
        
    }
}
