<?php
/**
 * MUPolls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUPolls
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * Installer base class.
 */
class MUPolls_Base_Installer extends Zikula_AbstractInstaller
{
    /**
     * Install the MUPolls application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {
        // create all tables from according entity definitions
        try {
            DoctrineHelper::createSchema($this->entityManager, $this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                return LogUtil::registerError($this->__('Doctrine Exception') . ': ' . $e->getMessage());
            }
            $returnMessage = $this->__f('An error was encountered while creating the tables for the %s extension.', array($this->getName()));
            if (!System::isDevelopmentMode()) {
                $returnMessage .= ' ' . $this->__('Please enable the development mode by editing the /config/config.php file in order to reveal the error details.');
            }
            return LogUtil::registerError($returnMessage);
        }
    
        // set up all our vars with initial values
        $this->setVar('kindOfVoting',  'session' );
    
        // create the default data
        $this->createDefaultData();
    
        // register persistent event handlers
        $this->registerPersistentEventHandlers();
    
        // register hook subscriber bundles
        HookUtil::registerSubscriberBundles($this->version->getHookSubscriberBundles());
        
    
        // initialisation successful
        return true;
    }
    
    /**
     * Upgrade the MUPolls application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldVersion Version to upgrade from.
     *
     * @return boolean True on success, false otherwise.
     */
    public function upgrade($oldVersion)
    {
    /*
        // Upgrade dependent on old version number
        switch ($oldVersion) {
            case '1.0.0':
                // do something
                // ...
                // update the database schema
                try {
                    DoctrineHelper::updateSchema($this->entityManager, $this->listEntityClasses());
                } catch (\Exception $e) {
                    if (System::isDevelopmentMode()) {
                        return LogUtil::registerError($this->__('Doctrine Exception') . ': ' . $e->getMessage());
                    }
                    return LogUtil::registerError($this->__f('An error was encountered while updating tables for the %s extension.', array($this->getName())));
                }
        }
    */
    
        // update successful
        return true;
    }
    
    /**
     * Uninstall MUPolls.
     *
     * @return boolean True on success, false otherwise.
     */
    public function uninstall()
    {
        // delete stored object workflows
        $result = Zikula_Workflow_Util::deleteWorkflowsForModule($this->getName());
        if ($result === false) {
            return LogUtil::registerError($this->__f('An error was encountered while removing stored object workflows for the %s extension.', array($this->getName())));
        }
    
        try {
            DoctrineHelper::dropSchema($this->entityManager, $this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                return LogUtil::registerError($this->__('Doctrine Exception') . ': ' . $e->getMessage());
            }
            return LogUtil::registerError($this->__f('An error was encountered while dropping tables for the %s extension.', array($this->getName())));
        }
    
        // unregister persistent event handlers
        EventUtil::unregisterPersistentModuleHandlers($this->name);
    
        // unregister hook subscriber bundles
        HookUtil::unregisterSubscriberBundles($this->version->getHookSubscriberBundles());
        
    
        // remove all module vars
        $this->delVars();
    
        // uninstallation successful
        return true;
    }
    
    /**
     * Build array with all entity classes for MUPolls.
     *
     * @return array list of class names.
     */
    protected function listEntityClasses()
    {
        $classNames = array();
        $classNames[] = 'MUPolls_Entity_Option';
        $classNames[] = 'MUPolls_Entity_OptionTranslation';
        $classNames[] = 'MUPolls_Entity_Poll';
        $classNames[] = 'MUPolls_Entity_PollTranslation';
        $classNames[] = 'MUPolls_Entity_Vote';
    
        return $classNames;
    }
    
    /**
     * Create the default data for MUPolls.
     *
     * @return void
     */
    protected function createDefaultData()
    {
        $entityClass = 'MUPolls_Entity_Option';
        $this->entityManager->getRepository($entityClass)->truncateTable();
        $entityClass = 'MUPolls_Entity_Poll';
        $this->entityManager->getRepository($entityClass)->truncateTable();
        $entityClass = 'MUPolls_Entity_Vote';
        $this->entityManager->getRepository($entityClass)->truncateTable();
    }
    
    /**
     * Register persistent event handlers.
     * These are listeners for external events of the core and other modules.
     */
    protected function registerPersistentEventHandlers()
    {
        // core -> 
        EventUtil::registerPersistentModuleHandler('MUPolls', 'api.method_not_found', array('MUPolls_Listener_Core', 'apiMethodNotFound'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'core.preinit', array('MUPolls_Listener_Core', 'preInit'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'core.init', array('MUPolls_Listener_Core', 'init'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'core.postinit', array('MUPolls_Listener_Core', 'postInit'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'controller.method_not_found', array('MUPolls_Listener_Core', 'controllerMethodNotFound'));
    
        // front controller -> MUPolls_Listener_FrontController
        EventUtil::registerPersistentModuleHandler('MUPolls', 'frontcontroller.predispatch', array('MUPolls_Listener_FrontController', 'preDispatch'));
    
        // installer -> MUPolls_Listener_Installer
        EventUtil::registerPersistentModuleHandler('MUPolls', 'installer.module.installed', array('MUPolls_Listener_Installer', 'moduleInstalled'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'installer.module.upgraded', array('MUPolls_Listener_Installer', 'moduleUpgraded'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'installer.module.uninstalled', array('MUPolls_Listener_Installer', 'moduleUninstalled'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'installer.subscriberarea.uninstalled', array('MUPolls_Listener_Installer', 'subscriberAreaUninstalled'));
    
        // modules -> MUPolls_Listener_ModuleDispatch
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module_dispatch.postloadgeneric', array('MUPolls_Listener_ModuleDispatch', 'postLoadGeneric'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module_dispatch.preexecute', array('MUPolls_Listener_ModuleDispatch', 'preExecute'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module_dispatch.postexecute', array('MUPolls_Listener_ModuleDispatch', 'postExecute'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module_dispatch.custom_classname', array('MUPolls_Listener_ModuleDispatch', 'customClassname'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module_dispatch.service_links', array('MUPolls_Listener_ModuleDispatch', 'serviceLinks'));
    
        // mailer -> MUPolls_Listener_Mailer
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module.mailer.api.sendmessage', array('MUPolls_Listener_Mailer', 'sendMessage'));
    
        // page -> MUPolls_Listener_Page
        EventUtil::registerPersistentModuleHandler('MUPolls', 'pageutil.addvar_filter', array('MUPolls_Listener_Page', 'pageutilAddvarFilter'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'system.outputfilter', array('MUPolls_Listener_Page', 'systemOutputfilter'));
    
        // errors -> MUPolls_Listener_Errors
        EventUtil::registerPersistentModuleHandler('MUPolls', 'setup.errorreporting', array('MUPolls_Listener_Errors', 'setupErrorReporting'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'systemerror', array('MUPolls_Listener_Errors', 'systemError'));
    
        // theme -> MUPolls_Listener_Theme
        EventUtil::registerPersistentModuleHandler('MUPolls', 'theme.preinit', array('MUPolls_Listener_Theme', 'preInit'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'theme.init', array('MUPolls_Listener_Theme', 'init'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'theme.load_config', array('MUPolls_Listener_Theme', 'loadConfig'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'theme.prefetch', array('MUPolls_Listener_Theme', 'preFetch'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'theme.postfetch', array('MUPolls_Listener_Theme', 'postFetch'));
    
        // view -> MUPolls_Listener_View
        EventUtil::registerPersistentModuleHandler('MUPolls', 'view.init', array('MUPolls_Listener_View', 'init'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'view.postfetch', array('MUPolls_Listener_View', 'postFetch'));
    
        // user login -> MUPolls_Listener_UserLogin
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module.users.ui.login.started', array('MUPolls_Listener_UserLogin', 'started'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module.users.ui.login.veto', array('MUPolls_Listener_UserLogin', 'veto'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module.users.ui.login.succeeded', array('MUPolls_Listener_UserLogin', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module.users.ui.login.failed', array('MUPolls_Listener_UserLogin', 'failed'));
    
        // user logout -> MUPolls_Listener_UserLogout
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module.users.ui.logout.succeeded', array('MUPolls_Listener_UserLogout', 'succeeded'));
    
        // user -> MUPolls_Listener_User
        EventUtil::registerPersistentModuleHandler('MUPolls', 'user.gettheme', array('MUPolls_Listener_User', 'getTheme'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'user.account.create', array('MUPolls_Listener_User', 'create'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'user.account.update', array('MUPolls_Listener_User', 'update'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'user.account.delete', array('MUPolls_Listener_User', 'delete'));
    
        // registration -> MUPolls_Listener_UserRegistration
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module.users.ui.registration.started', array('MUPolls_Listener_UserRegistration', 'started'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module.users.ui.registration.succeeded', array('MUPolls_Listener_UserRegistration', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module.users.ui.registration.failed', array('MUPolls_Listener_UserRegistration', 'failed'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'user.registration.create', array('MUPolls_Listener_UserRegistration', 'create'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'user.registration.update', array('MUPolls_Listener_UserRegistration', 'update'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'user.registration.delete', array('MUPolls_Listener_UserRegistration', 'delete'));
    
        // users module -> MUPolls_Listener_Users
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module.users.config.updated', array('MUPolls_Listener_Users', 'configUpdated'));
    
        // group -> MUPolls_Listener_Group
        EventUtil::registerPersistentModuleHandler('MUPolls', 'group.create', array('MUPolls_Listener_Group', 'create'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'group.update', array('MUPolls_Listener_Group', 'update'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'group.delete', array('MUPolls_Listener_Group', 'delete'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'group.adduser', array('MUPolls_Listener_Group', 'addUser'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'group.removeuser', array('MUPolls_Listener_Group', 'removeUser'));
    
        // special purposes and 3rd party api support -> MUPolls_Listener_ThirdParty
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module.content.gettypes', array('MUPolls_Listener_ThirdParty', 'contentGetTypes'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'module.scribite.editorhelpers', array('MUPolls_Listener_ThirdParty', 'getEditorHelpers'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'moduleplugin.tinymce.externalplugins', array('MUPolls_Listener_ThirdParty', 'getTinyMcePlugins'));
        EventUtil::registerPersistentModuleHandler('MUPolls', 'moduleplugin.ckeditor.externalplugins', array('MUPolls_Listener_ThirdParty', 'getCKEditorPlugins'));
    }
}
