<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\PollsModule\Form\DataTransformer;

use MU\PollsModule\Form\DataTransformer\Base\AbstractUserFieldTransformer;

/**
 * User field transformer implementation class.
 *
 * This data transformer treats user fields.
 */
class UserFieldTransformer extends AbstractUserFieldTransformer
{
    // feel free to add your customisation here
}
