<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\PollsModule\ContentType;

use MU\PollsModule\ContentType\Base\AbstractItem;

/**
 * Generic single item display content plugin implementation class.
 */
class Item extends AbstractItem
{
    // feel free to extend the content type here
}
