<?php
/**
 * MUPolls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUPolls
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the base validation class for option entities.
 */
abstract class MUPolls_Entity_Validator_Base_AbstractOption extends MUPolls_Validator
{
    /**
     * Performs all validation rules.
     *
     * @return mixed either array with error information or true on success
     */
    public function validateAll()
    {
        $errorInfo = array(
            'message' => '',
            'code' => 0,
            'debugArray' => array()
        );
        $dom = ZLanguage::getModuleDomain('MUPolls');
        if (!$this->isValidInteger('id')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('id'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('id', 9)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('id', 9), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('workflowState')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('workflow state'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('title', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('title', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('title')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('title'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('colorOfOption', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('color of option', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotContaining('colorOfOption', ' ')) {
            $errorInfo['message'] = __f('Error! Field value must not contain space chars (%s).', array('color of option'), $dom);
            return $errorInfo;
        }
        if ($this->entity['colorOfOption'] != '' && !$this->isValidHtmlColour('colorOfOption')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid html colour code [#123 or #123456] (%s).', array('color of option'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidInteger('idOfPoll')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('id of poll'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotEmpty('idOfPoll')) {
            $errorInfo['message'] = __f('Error! Field value must not be 0 (%s).', array('id of poll'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('idOfPoll', 11)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('id of poll', 11), $dom);
            return $errorInfo;
        }
    
        return true;
    }
    
    /**
     * Checks for unique values.
     *
     * This method determines if there already exist options with the same option.
     *
     * @param string $fieldName The name of the property to be checked
     *
     * @return boolean result of this check, true if the given option does not already exist
     */
    public function isUniqueValue($fieldName)
    {
        if ($this->entity[$fieldName] === '') {
            return false;
        }
    
        $entityClass = 'MUPolls_Entity_Option';
        $serviceManager = ServiceUtil::getManager();
        $entityManager = $serviceManager->getService('doctrine.entitymanager');
        $repository = $entityManager->getRepository($entityClass);
    
        $excludeid = $this->entity['id'];
    
        return $repository->detectUniqueState($fieldName, $this->entity[$fieldName], $excludeid);
    }
    
    /**
     * Gets the entity.
     *
     * @return Zikula_EntityAccess
     */
    public function getEntity()
    {
        return $this->entity;
    }
    
    /**
     * Sets the entity.
     *
     * @param Zikula_EntityAccess $entity
     *
     * @return void
     */
    public function setEntity(Zikula_EntityAccess $entity = null)
    {
        $this->entity = $entity;
    }
    
}
