<?php
/**
 * MUPolls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUPolls
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

/**
 * MUPolls vote needle information.
 *
 * @param none
 *
 * @return string with short usage description
 */
function MUPolls_needleapi_vote_baseInfo()
{
    $info = array(
        // module name
        'module'  => 'MUPolls',
        // possible needles
        'info'    => 'MUPOLLS{VOTES|VOTE-voteId}',
        // whether a reverse lookup is possible, needs MUPolls_needleapi_vote_inspect() function
        'inspect' => false
    );

    return $info;
}
