<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\PollsModule\HookProvider;

use MU\PollsModule\HookProvider\Base\AbstractPollUiHooksProvider;

/**
 * Implementation class for ui hooks provider.
 */
class PollUiHooksProvider extends AbstractPollUiHooksProvider
{
    // feel free to add your own convenience methods here
}
