<?php
/**
 * MUPolls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUPolls
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * This handler class handles the page events of the Form called by the mUPolls_option_edit() function.
 * It aims on the option object type.
 */
class MUPolls_Form_Handler_Option_Edit extends MUPolls_Form_Handler_Option_Base_Edit
{
    // feel free to extend the base handler class here
}
