<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\PollsModule\Form\Base;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use Zikula\ExtensionsModule\Api\VariableApi;

/**
 * Configuration form type base class.
 */
abstract class AbstractAppSettingsType extends AbstractType
{
    use TranslatorTrait;

    /**
     * @var VariableApi
     */
    protected $variableApi;

    /**
     * @var array
     */
    protected $modVars;

    /**
     * AppSettingsType constructor.
     *
     * @param TranslatorInterface  $translator  Translator service instance
     * @param VariableApi          $variableApi VariableApi service instance
     */
    public function __construct(
        TranslatorInterface $translator,
        VariableApi $variableApi
    ) {
        $this->setTranslator($translator);
        $this->variableApi = $variableApi;
        $this->modVars = $this->variableApi->getAll('MUPollsModule');
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

    /**
     * @inheritDoc
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->addMySettingsFields($builder, $options);
        $this->addListViewsFields($builder, $options);

        $builder
            ->add('save', 'Symfony\Component\Form\Extension\Core\Type\SubmitType', [
                'label' => $this->__('Update configuration'),
                'icon' => 'fa-check',
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ])
            ->add('cancel', 'Symfony\Component\Form\Extension\Core\Type\SubmitType', [
                'label' => $this->__('Cancel'),
                'icon' => 'fa-times',
                'attr' => [
                    'class' => 'btn btn-default',
                    'formnovalidate' => 'formnovalidate'
                ]
            ])
        ;
    }

    /**
     * Adds fields for my settings fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addMySettingsFields(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('kindOfVoting', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', [
                'label' => $this->__('Kind of voting') . ':',
                'required' => false,
                'data' => isset($this->modVars['kindOfVoting']) ? $this->modVars['kindOfVoting'] : '',
                'empty_data' => 'Session',
                'attr' => [
                    'title' => $this->__('Choose the kind of voting.')
                ],'choices' => [
                    $this->__('Cookie') => 'cookie'
                    ,$this->__('Session') => 'session'
                    ,$this->__('User') => 'user'
                ],
                'choices_as_values' => true,
                'multiple' => false
            ])
        ;
    }

    /**
     * Adds fields for list views fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addListViewsFields(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('optionEntriesPerPage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Option entries per page') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The amount of options shown per page')
                ],
                'help' => $this->__('The amount of options shown per page'),
                'required' => false,
                'data' => isset($this->modVars['optionEntriesPerPage']) ? $this->modVars['optionEntriesPerPage'] : '',
                'empty_data' => intval('10'),
                'attr' => [
                    'maxlength' => 255,
                    'title' => $this->__('Enter the option entries per page.') . ' ' . $this->__('Only digits are allowed.')
                ],'scale' => 0
            ])
            ->add('linkOwnOptionsOnAccountPage', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
                'label' => $this->__('Link own options on account page') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Whether to add a link to options of the current user on his account page')
                ],
                'help' => $this->__('Whether to add a link to options of the current user on his account page'),
                'required' => false,
                'data' => (bool)(isset($this->modVars['linkOwnOptionsOnAccountPage']) ? $this->modVars['linkOwnOptionsOnAccountPage'] : true),
                'attr' => [
                    'title' => $this->__('The link own options on account page option.')
                ],
            ])
            ->add('pollEntriesPerPage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Poll entries per page') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The amount of polls shown per page')
                ],
                'help' => $this->__('The amount of polls shown per page'),
                'required' => false,
                'data' => isset($this->modVars['pollEntriesPerPage']) ? $this->modVars['pollEntriesPerPage'] : '',
                'empty_data' => intval('10'),
                'attr' => [
                    'maxlength' => 255,
                    'title' => $this->__('Enter the poll entries per page.') . ' ' . $this->__('Only digits are allowed.')
                ],'scale' => 0
            ])
            ->add('linkOwnPollsOnAccountPage', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
                'label' => $this->__('Link own polls on account page') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Whether to add a link to polls of the current user on his account page')
                ],
                'help' => $this->__('Whether to add a link to polls of the current user on his account page'),
                'required' => false,
                'data' => (bool)(isset($this->modVars['linkOwnPollsOnAccountPage']) ? $this->modVars['linkOwnPollsOnAccountPage'] : true),
                'attr' => [
                    'title' => $this->__('The link own polls on account page option.')
                ],
            ])
            ->add('voteEntriesPerPage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Vote entries per page') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The amount of votes shown per page')
                ],
                'help' => $this->__('The amount of votes shown per page'),
                'required' => false,
                'data' => isset($this->modVars['voteEntriesPerPage']) ? $this->modVars['voteEntriesPerPage'] : '',
                'empty_data' => intval('10'),
                'attr' => [
                    'maxlength' => 255,
                    'title' => $this->__('Enter the vote entries per page.') . ' ' . $this->__('Only digits are allowed.')
                ],'scale' => 0
            ])
            ->add('linkOwnVotesOnAccountPage', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
                'label' => $this->__('Link own votes on account page') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Whether to add a link to votes of the current user on his account page')
                ],
                'help' => $this->__('Whether to add a link to votes of the current user on his account page'),
                'required' => false,
                'data' => (bool)(isset($this->modVars['linkOwnVotesOnAccountPage']) ? $this->modVars['linkOwnVotesOnAccountPage'] : true),
                'attr' => [
                    'title' => $this->__('The link own votes on account page option.')
                ],
            ])
        ;
    }

    /**
     * @inheritDoc
     */
    public function getBlockPrefix()
    {
        return 'mupollsmodule_appsettings';
    }
}
