services:
    # Entity factory
    mu_polls_module.entity_factory:
        class: MU\PollsModule\Entity\Factory\PollsFactory
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@mu_polls_module.entity_initialiser"
    # Entity initialiser
    mu_polls_module.entity_initialiser:
        class: MU\PollsModule\Entity\Factory\EntityInitialiser
