services:
    # Event subscribers and listeners
    mu_polls_module.entity_lifecycle_listener:
        class: MU\PollsModule\Listener\EntityLifecycleListener
        arguments:
            - "@service_container"
            - "@event_dispatcher"
            - "@logger"
        tags: ['doctrine.event_subscriber']
    
    mu_polls_module.kernel_listener:
        class: MU\PollsModule\Listener\KernelListener
        tags: ['kernel.event_subscriber']
    
    mu_polls_module.installer_listener:
        class: MU\PollsModule\Listener\InstallerListener
        arguments:
            - "@mu_polls_module.entity_factory"
        tags: ['kernel.event_subscriber']
    
    mu_polls_module.moduledispatch_listener:
        class: MU\PollsModule\Listener\ModuleDispatchListener
        tags: ['kernel.event_subscriber']
    
    mu_polls_module.mailer_listener:
        class: MU\PollsModule\Listener\MailerListener
        tags: ['kernel.event_subscriber']
    
    mu_polls_module.theme_listener:
        class: MU\PollsModule\Listener\ThemeListener
        tags: ['kernel.event_subscriber']
    
    mu_polls_module.userlogin_listener:
        class: MU\PollsModule\Listener\UserLoginListener
        tags: ['kernel.event_subscriber']
    
    mu_polls_module.userlogout_listener:
        class: MU\PollsModule\Listener\UserLogoutListener
        tags: ['kernel.event_subscriber']
    
    mu_polls_module.user_listener:
        class: MU\PollsModule\Listener\UserListener
        arguments:
            - "@translator.default"
            - "@mu_polls_module.entity_factory"
            - "@zikula_users_module.current_user"
            - "@logger"
        tags: ['kernel.event_subscriber']
    
    mu_polls_module.userregistration_listener:
        class: MU\PollsModule\Listener\UserRegistrationListener
        tags: ['kernel.event_subscriber']
    
    mu_polls_module.users_listener:
        class: MU\PollsModule\Listener\UsersListener
        tags: ['kernel.event_subscriber']
    
    mu_polls_module.group_listener:
        class: MU\PollsModule\Listener\GroupListener
        tags: ['kernel.event_subscriber']
    
    mu_polls_module.thirdparty_listener:
        class: MU\PollsModule\Listener\ThirdPartyListener
        arguments:
            - "@mu_polls_module.workflow_helper"
        tags: ['kernel.event_subscriber']
    
    mu_polls_module.workflow_events_listener:
        class: MU\PollsModule\Listener\WorkflowEventsListener
        arguments:
            - "@mu_polls_module.entity_factory"
            - "@mu_polls_module.permission_helper"
            - "@mu_polls_module.notification_helper"
        tags: ['kernel.event_subscriber']
    
