services:
    # Form types
    
    mu_polls_module.form.type.optionquicknav:
        class: MU\PollsModule\Form\Type\QuickNavigation\OptionQuickNavType
        arguments:
            - "@translator.default"
            - "@mu_polls_module.listentries_helper"
            - "@mu_polls_module.feature_activation_helper"
        tags: ['form.type']
    
    mu_polls_module.form.type.pollquicknav:
        class: MU\PollsModule\Form\Type\QuickNavigation\PollQuickNavType
        arguments:
            - "@translator.default"
            - "@mu_polls_module.listentries_helper"
            - "@mu_polls_module.feature_activation_helper"
        tags: ['form.type']
    
    mu_polls_module.form.type.votequicknav:
        class: MU\PollsModule\Form\Type\QuickNavigation\VoteQuickNavType
        arguments:
            - "@translator.default"
            - "@mu_polls_module.listentries_helper"
            - "@mu_polls_module.feature_activation_helper"
        tags: ['form.type']
    
    mu_polls_module.form.handler.common:
        abstract: true
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@zikula_groups_module.group_application_repository"
            - "@mu_polls_module.entity_factory"
            - "@mu_polls_module.controller_helper"
            - "@mu_polls_module.model_helper"
            - "@mu_polls_module.permission_helper"
            - "@mu_polls_module.workflow_helper"
            - "@mu_polls_module.hook_helper"
            - "@mu_polls_module.translatable_helper"
            - "@mu_polls_module.feature_activation_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
    
    
    mu_polls_module.form.handler.option:
        class: MU\PollsModule\Form\Handler\Option\EditHandler
        parent: mu_polls_module.form.handler.common
    
    mu_polls_module.form.type.option:
        class: MU\PollsModule\Form\Type\OptionType
        arguments:
            - "@translator.default"
            - "@mu_polls_module.entity_factory"
            - "@zikula_extensions_module.api.variable"
            - "@mu_polls_module.translatable_helper"
            - "@mu_polls_module.listentries_helper"
            - "@mu_polls_module.feature_activation_helper"
        tags: ['form.type']
    
    mu_polls_module.form.handler.poll:
        class: MU\PollsModule\Form\Handler\Poll\EditHandler
        parent: mu_polls_module.form.handler.common
    
    mu_polls_module.form.type.poll:
        class: MU\PollsModule\Form\Type\PollType
        arguments:
            - "@translator.default"
            - "@mu_polls_module.entity_factory"
            - "@zikula_extensions_module.api.variable"
            - "@mu_polls_module.translatable_helper"
            - "@mu_polls_module.listentries_helper"
            - "@mu_polls_module.feature_activation_helper"
        tags: ['form.type']
    
    mu_polls_module.form.handler.vote:
        class: MU\PollsModule\Form\Handler\Vote\EditHandler
        parent: mu_polls_module.form.handler.common
    
    mu_polls_module.form.type.vote:
        class: MU\PollsModule\Form\Type\VoteType
        arguments:
            - "@translator.default"
            - "@mu_polls_module.entity_factory"
            - "@mu_polls_module.listentries_helper"
            - "@mu_polls_module.feature_activation_helper"
        tags: ['form.type']
    
    mu_polls_module.form.type.block.itemlist:
        class: MU\PollsModule\Block\Form\Type\ItemListBlockType
        arguments:
            - "@translator.default"
        tags: ['form.type']
    
    mu_polls_module.form.type.block.item:
        class: MU\PollsModule\Block\Form\Type\ItemBlockType
        arguments:
            - "@translator.default"
            - "@mu_polls_module.entity_factory"
            - "@mu_polls_module.entity_display_helper"
        tags: ['form.type']
    
    mu_polls_module.form.type.optionfinder:
        class: MU\PollsModule\Form\Type\Finder\OptionFinderType
        arguments:
            - "@translator.default"
            - "@mu_polls_module.feature_activation_helper"
        tags: ['form.type']
    
    mu_polls_module.form.type.pollfinder:
        class: MU\PollsModule\Form\Type\Finder\PollFinderType
        arguments:
            - "@translator.default"
            - "@mu_polls_module.feature_activation_helper"
        tags: ['form.type']
    
    mu_polls_module.form.type.votefinder:
        class: MU\PollsModule\Form\Type\Finder\VoteFinderType
        arguments:
            - "@translator.default"
            - "@mu_polls_module.feature_activation_helper"
        tags: ['form.type']
    
    mu_polls_module.form.type.config:
        class: MU\PollsModule\Form\Type\ConfigType
        arguments:
            - "@translator.default"
            - "@mu_polls_module.listentries_helper"
        tags: ['form.type']
