services:
    # Helper services
    mu_polls_module.controller_helper:
        class: MU\PollsModule\Helper\ControllerHelper
        arguments:
            - "@request_stack"
            - "@form.factory"
            - "@zikula_extensions_module.api.variable"
            - "@mu_polls_module.entity_factory"
            - "@mu_polls_module.model_helper"
            - "@mu_polls_module.feature_activation_helper"
    
    mu_polls_module.feature_activation_helper:
        class: MU\PollsModule\Helper\FeatureActivationHelper
    
    mu_polls_module.hook_helper:
        class: MU\PollsModule\Helper\HookHelper
        arguments:
            - "@hook_dispatcher"
    
    mu_polls_module.listentries_helper:
        class: MU\PollsModule\Helper\ListEntriesHelper
        arguments:
            - "@translator.default"
    
    mu_polls_module.model_helper:
        class: MU\PollsModule\Helper\ModelHelper
        arguments:
            - "@mu_polls_module.entity_factory"
    
    mu_polls_module.search_helper:
        class: MU\PollsModule\Helper\SearchHelper
        arguments:
            - "@translator.default"
            - "@zikula_permissions_module.api.permission"
            - "@templating.engine.twig"
            - "@session"
            - "@request_stack"
            - "@mu_polls_module.entity_factory"
            - "@mu_polls_module.controller_helper"
        tags:
            - { name: zikula.searchable_module, bundleName: MUPollsModule }
    
    mu_polls_module.translatable_helper:
        class: MU\PollsModule\Helper\TranslatableHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_settings_module.locale_api"
            - "@mu_polls_module.entity_factory"
    
    mu_polls_module.view_helper:
        class: MU\PollsModule\Helper\ViewHelper
        arguments:
            - "@twig"
            - "@twig.loader"
            - "@request_stack"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_core.common.theme.pagevars"
            - "@mu_polls_module.controller_helper"
    
    mu_polls_module.workflow_helper:
        class: MU\PollsModule\Helper\WorkflowHelper
        arguments:
            - "@translator.default"
            - "@mu_polls_module.listentries_helper"
