services:
    mu_polls_module.link_container:
        class: MU\PollsModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_extensions_module.api.variable"
            - "@mu_polls_module.controller_helper"
            - "@mu_polls_module.permission_helper"
        tags: ['zikula.link_container']
