services:
    mu_polls_module.link_container:
        class: MU\PollsModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@mu_polls_module.controller_helper"
        tags:
            - { name: zikula.link_container }
