services:
    # Twig extension
    mu_polls_module.twig_extension:
        class: MU\PollsModule\Twig\TwigExtension
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.user_repository"
            - "@mu_polls_module.workflow_helper"
            - "@mu_polls_module.listentries_helper"
        public: false
        tags:
            - { name: twig.extension }
