services:
    # Custom validators
    mu_polls_module.validator.list_entry.validator:
        class: MU\PollsModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@mu_polls_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: mu_polls_module.validator.list_entry.validator }
