<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\PollsModule\Form\Type;

use MU\PollsModule\Form\Type\Base\AbstractPollType;

/**
 * Poll editing form type implementation class.
 */
class PollType extends AbstractPollType
{
    // feel free to extend the poll editing form type class here
}
