<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\PollsModule\Form\Type;

use MU\PollsModule\Form\Type\Base\AbstractVoteType;

/**
 * Vote editing form type implementation class.
 */
class VoteType extends AbstractVoteType
{
    // feel free to extend the vote editing form type class here
}
