<?php
/**
 * MUPolls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUPolls
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * Date value input. Not ready for datetime fields, only for raw dates.
 *
 * You can also use all of the features from the Zikula_Form_Plugin_DateInput plugin since
 * the date input inherits from it.
 */
class MUPolls_Form_Plugin_DateInput extends MUPolls_Form_Plugin_Base_DateInput
{
    // feel free to add your customisation here
}
