<?php
/**
 * MUPolls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUPolls
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

/**
 * Item selector plugin implementation class.
 */
class MUPolls_Form_Plugin_ItemSelector extends MUPolls_Form_Plugin_Base_AbstractItemSelector
{
    // feel free to add your customisation here
}
