<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\PollsModule\Form\Type\QuickNavigation;

use MU\PollsModule\Form\Type\QuickNavigation\Base\AbstractVoteQuickNavType;

/**
 * Vote quick navigation form type implementation class.
 */
class VoteQuickNavType extends AbstractVoteQuickNavType
{
    // feel free to extend the base form type class here
}
