<?php
/**
 * MUPolls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUPolls
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

/**
 * Paginator switch implementation class for 1.3.x modules.
 */
class MUPolls_Paginator_LegacyPaginator extends MUPolls_Paginator_Base_AbstractLegacyPaginator
{
    // extend the paginator class here if desired
}
