<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\PollsModule\Container\Base;

use Zikula\Bundle\HookBundle\AbstractHookContainer as ZikulaHookContainer;
use Zikula\Bundle\HookBundle\Bundle\SubscriberBundle;

/**
 * Base class for hook container methods.
 */
abstract class AbstractHookContainer extends ZikulaHookContainer
{
    /**
     * Define the hook bundles supported by this module.
     *
     * @return void
     */
    protected function setupHookBundles()
    {
        $bundle = new SubscriberBundle('MUPollsModule', 'subscriber.mupollsmodule.ui_hooks.options', 'ui_hooks', $this->__('mupollsmodule. Options Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'mupollsmodule.ui_hooks.options.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'mupollsmodule.ui_hooks.options.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'mupollsmodule.ui_hooks.options.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'mupollsmodule.ui_hooks.options.validate_edit');
        // Validate input from an ui delete form.
        $bundle->addEvent('validate_delete', 'mupollsmodule.ui_hooks.options.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'mupollsmodule.ui_hooks.options.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'mupollsmodule.ui_hooks.options.process_delete');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('MUPollsModule', 'subscriber.mupollsmodule.filter_hooks.options', 'filter_hooks', $this->__('mupollsmodule. Options Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'mupollsmodule.filter_hooks.options.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('MUPollsModule', 'subscriber.mupollsmodule.ui_hooks.polls', 'ui_hooks', $this->__('mupollsmodule. Polls Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'mupollsmodule.ui_hooks.polls.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'mupollsmodule.ui_hooks.polls.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'mupollsmodule.ui_hooks.polls.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'mupollsmodule.ui_hooks.polls.validate_edit');
        // Validate input from an ui delete form.
        $bundle->addEvent('validate_delete', 'mupollsmodule.ui_hooks.polls.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'mupollsmodule.ui_hooks.polls.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'mupollsmodule.ui_hooks.polls.process_delete');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('MUPollsModule', 'subscriber.mupollsmodule.filter_hooks.polls', 'filter_hooks', $this->__('mupollsmodule. Polls Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'mupollsmodule.filter_hooks.polls.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('MUPollsModule', 'subscriber.mupollsmodule.ui_hooks.votes', 'ui_hooks', $this->__('mupollsmodule. Votes Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'mupollsmodule.ui_hooks.votes.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'mupollsmodule.ui_hooks.votes.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'mupollsmodule.ui_hooks.votes.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'mupollsmodule.ui_hooks.votes.validate_edit');
        // Validate input from an ui delete form.
        $bundle->addEvent('validate_delete', 'mupollsmodule.ui_hooks.votes.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'mupollsmodule.ui_hooks.votes.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'mupollsmodule.ui_hooks.votes.process_delete');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('MUPollsModule', 'subscriber.mupollsmodule.filter_hooks.votes', 'filter_hooks', $this->__('mupollsmodule. Votes Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'mupollsmodule.filter_hooks.votes.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        
    }
}
