<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\PollsModule\Container\Base;

use Symfony\Component\Routing\RouterInterface;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use Zikula\Core\Doctrine\EntityAccess;
use Zikula\Core\LinkContainer\LinkContainerInterface;
use Zikula\ExtensionsModule\Api\ApiInterface\VariableApiInterface;
use MU\PollsModule\Helper\ControllerHelper;
use MU\PollsModule\Helper\PermissionHelper;

/**
 * This is the link container service implementation class.
 */
abstract class AbstractLinkContainer implements LinkContainerInterface
{
    use TranslatorTrait;

    /**
     * @var RouterInterface
     */
    protected $router;

    /**
     * @var VariableApiInterface
     */
    protected $variableApi;

    /**
     * @var ControllerHelper
     */
    protected $controllerHelper;

    /**
     * @var PermissionHelper
     */
    protected $permissionHelper;

    /**
     * LinkContainer constructor.
     *
     * @param TranslatorInterface  $translator       Translator service instance
     * @param Routerinterface      $router           Router service instance
     * @param VariableApiInterface $variableApi      VariableApi service instance
     * @param ControllerHelper     $controllerHelper ControllerHelper service instance
     * @param PermissionHelper     $permissionHelper PermissionHelper service instance
     */
    public function __construct(
        TranslatorInterface $translator,
        RouterInterface $router,
        VariableApiInterface $variableApi,
        ControllerHelper $controllerHelper,
        PermissionHelper $permissionHelper
    ) {
        $this->setTranslator($translator);
        $this->router = $router;
        $this->variableApi = $variableApi;
        $this->controllerHelper = $controllerHelper;
        $this->permissionHelper = $permissionHelper;
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

    /**
     * Returns available header links.
     *
     * @param string $type The type to collect links for
     *
     * @return array List of header links
     */
    public function getLinks($type = LinkContainerInterface::TYPE_ADMIN)
    {
        $contextArgs = ['api' => 'linkContainer', 'action' => 'getLinks'];
        $allowedObjectTypes = $this->controllerHelper->getObjectTypes('api', $contextArgs);

        $permLevel = LinkContainerInterface::TYPE_ADMIN == $type ? ACCESS_ADMIN : ACCESS_READ;

        // Create an array of links to return
        $links = [];

        if (LinkContainerInterface::TYPE_ACCOUNT == $type) {
            if (!$this->permissionHelper->hasPermission(ACCESS_OVERVIEW)) {
                return $links;
            }

            if (true === $this->variableApi->get('MUPollsModule', 'linkOwnOptionsOnAccountPage', true)) {
                $objectType = 'option';
                if ($this->permissionHelper->hasComponentPermission($objectType, ACCESS_READ)) {
                    $links[] = [
                        'url' => $this->router->generate('mupollsmodule_' . strtolower($objectType) . '_view', ['own' => 1]),
                        'text' => $this->__('My options', 'mupollsmodule'),
                        'icon' => 'list-alt'
                    ];
                }
            }

            if (true === $this->variableApi->get('MUPollsModule', 'linkOwnPollsOnAccountPage', true)) {
                $objectType = 'poll';
                if ($this->permissionHelper->hasComponentPermission($objectType, ACCESS_READ)) {
                    $links[] = [
                        'url' => $this->router->generate('mupollsmodule_' . strtolower($objectType) . '_view', ['own' => 1]),
                        'text' => $this->__('My polls', 'mupollsmodule'),
                        'icon' => 'list-alt'
                    ];
                }
            }

            if (true === $this->variableApi->get('MUPollsModule', 'linkOwnVotesOnAccountPage', true)) {
                $objectType = 'vote';
                if ($this->permissionHelper->hasComponentPermission($objectType, ACCESS_READ)) {
                    $links[] = [
                        'url' => $this->router->generate('mupollsmodule_' . strtolower($objectType) . '_view', ['own' => 1]),
                        'text' => $this->__('My votes', 'mupollsmodule'),
                        'icon' => 'list-alt'
                    ];
                }
            }

            if ($this->permissionHelper->hasPermission(ACCESS_ADMIN)) {
                $links[] = [
                    'url' => $this->router->generate('mupollsmodule_poll_adminindex'),
                    'text' => $this->__('Polls Backend', 'mupollsmodule'),
                    'icon' => 'wrench'
                ];
            }


            return $links;
        }

        $routeArea = LinkContainerInterface::TYPE_ADMIN == $type ? 'admin' : '';
        if (LinkContainerInterface::TYPE_ADMIN == $type) {
            if ($this->permissionHelper->hasPermission(ACCESS_READ)) {
                $links[] = [
                    'url' => $this->router->generate('mupollsmodule_poll_index'),
                    'text' => $this->__('Frontend', 'mupollsmodule'),
                    'title' => $this->__('Switch to user area.', 'mupollsmodule'),
                    'icon' => 'home'
                ];
            }
        } else {
            if ($this->permissionHelper->hasPermission(ACCESS_ADMIN)) {
                $links[] = [
                    'url' => $this->router->generate('mupollsmodule_poll_adminindex'),
                    'text' => $this->__('Backend', 'mupollsmodule'),
                    'title' => $this->__('Switch to administration area.', 'mupollsmodule'),
                    'icon' => 'wrench'
                ];
            }
        }
        
        if (in_array('option', $allowedObjectTypes)
            && $this->permissionHelper->hasComponentPermission('option', $permLevel)) {
            $links[] = [
                'url' => $this->router->generate('mupollsmodule_option_' . $routeArea . 'view'),
                'text' => $this->__('Options', 'mupollsmodule'),
                'title' => $this->__('Options list', 'mupollsmodule')
            ];
        }
        if (in_array('poll', $allowedObjectTypes)
            && $this->permissionHelper->hasComponentPermission('poll', $permLevel)) {
            $links[] = [
                'url' => $this->router->generate('mupollsmodule_poll_' . $routeArea . 'view'),
                'text' => $this->__('Polls', 'mupollsmodule'),
                'title' => $this->__('Polls list', 'mupollsmodule')
            ];
        }
        if (in_array('vote', $allowedObjectTypes)
            && $this->permissionHelper->hasComponentPermission('vote', $permLevel)) {
            $links[] = [
                'url' => $this->router->generate('mupollsmodule_vote_' . $routeArea . 'view'),
                'text' => $this->__('Votes', 'mupollsmodule'),
                'title' => $this->__('Votes list', 'mupollsmodule')
            ];
        }
        if ($routeArea == 'admin' && $this->permissionHelper->hasPermission(ACCESS_ADMIN)) {
            $links[] = [
                'url' => $this->router->generate('mupollsmodule_config_config'),
                'text' => $this->__('Settings', 'mupollsmodule'),
                'title' => $this->__('Manage settings for this application', 'mupollsmodule'),
                'icon' => 'wrench'
            ];
        }

        return $links;
    }

    /**
     * Returns the name of the providing bundle.
     *
     * @return string The bundle name
     */
    public function getBundleName()
    {
        return 'MUPollsModule';
    }
}
