<?php
/**
 * MUPolls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUPolls
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

/**
 * This class provides object meta data for the Tag module.
 */
class MUPolls_TaggedObjectMeta_MUPolls extends MUPolls_TaggedObjectMeta_Base_AbstractMUPolls
{
    // feel free to extend the tag support here
}
