<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\PollsModule\Form;

use MU\PollsModule\Form\Base\AbstractAppSettingsType;

/**
 * Configuration form type implementation class.
 */
class AppSettingsType extends AbstractAppSettingsType
{
    // feel free to extend the base form type class here
}
