modules/MUPolls/templates/option/main.tpl: config/templates/MUPolls/option/main.tpl
modules/MUPolls/templates/option/view.tpl: config/templates/MUPolls/option/view.tpl
modules/MUPolls/templates/option/viewQuickNav.tpl: config/templates/MUPolls/option/viewQuickNav.tpl
modules/MUPolls/templates/option/view.csv.tpl: config/templates/MUPolls/option/view.csv.tpl
modules/MUPolls/templates/option/view.rss.tpl: config/templates/MUPolls/option/view.rss.tpl
modules/MUPolls/templates/option/view.atom.tpl: config/templates/MUPolls/option/view.atom.tpl
modules/MUPolls/templates/option/view.xml.tpl: config/templates/MUPolls/option/view.xml.tpl
modules/MUPolls/templates/option/display.xml.tpl: config/templates/MUPolls/option/display.xml.tpl
modules/MUPolls/templates/option/include.xml.tpl: config/templates/MUPolls/option/include.xml.tpl
modules/MUPolls/templates/option/view.json.tpl: config/templates/MUPolls/option/view.json.tpl
modules/MUPolls/templates/option/display.json.tpl: config/templates/MUPolls/option/display.json.tpl
modules/MUPolls/templates/option/display.tpl: config/templates/MUPolls/option/display.tpl
modules/MUPolls/templates/option/delete.tpl: config/templates/MUPolls/option/delete.tpl
modules/MUPolls/templates/poll/main.tpl: config/templates/MUPolls/poll/main.tpl
modules/MUPolls/templates/poll/view.tpl: config/templates/MUPolls/poll/view.tpl
modules/MUPolls/templates/poll/viewQuickNav.tpl: config/templates/MUPolls/poll/viewQuickNav.tpl
modules/MUPolls/templates/poll/view.csv.tpl: config/templates/MUPolls/poll/view.csv.tpl
modules/MUPolls/templates/poll/view.rss.tpl: config/templates/MUPolls/poll/view.rss.tpl
modules/MUPolls/templates/poll/view.atom.tpl: config/templates/MUPolls/poll/view.atom.tpl
modules/MUPolls/templates/poll/view.xml.tpl: config/templates/MUPolls/poll/view.xml.tpl
modules/MUPolls/templates/poll/display.xml.tpl: config/templates/MUPolls/poll/display.xml.tpl
modules/MUPolls/templates/poll/include.xml.tpl: config/templates/MUPolls/poll/include.xml.tpl
modules/MUPolls/templates/poll/view.json.tpl: config/templates/MUPolls/poll/view.json.tpl
modules/MUPolls/templates/poll/display.json.tpl: config/templates/MUPolls/poll/display.json.tpl
modules/MUPolls/templates/poll/display.ics.tpl: config/templates/MUPolls/poll/display.ics.tpl
modules/MUPolls/templates/poll/display.tpl: config/templates/MUPolls/poll/display.tpl
modules/MUPolls/templates/poll/delete.tpl: config/templates/MUPolls/poll/delete.tpl
modules/MUPolls/templates/vote/main.tpl: config/templates/MUPolls/vote/main.tpl
modules/MUPolls/templates/vote/view.tpl: config/templates/MUPolls/vote/view.tpl
modules/MUPolls/templates/vote/viewQuickNav.tpl: config/templates/MUPolls/vote/viewQuickNav.tpl
modules/MUPolls/templates/vote/view.csv.tpl: config/templates/MUPolls/vote/view.csv.tpl
modules/MUPolls/templates/vote/view.rss.tpl: config/templates/MUPolls/vote/view.rss.tpl
modules/MUPolls/templates/vote/view.atom.tpl: config/templates/MUPolls/vote/view.atom.tpl
modules/MUPolls/templates/vote/view.xml.tpl: config/templates/MUPolls/vote/view.xml.tpl
modules/MUPolls/templates/vote/display.xml.tpl: config/templates/MUPolls/vote/display.xml.tpl
modules/MUPolls/templates/vote/include.xml.tpl: config/templates/MUPolls/vote/include.xml.tpl
modules/MUPolls/templates/vote/view.json.tpl: config/templates/MUPolls/vote/view.json.tpl
modules/MUPolls/templates/vote/display.json.tpl: config/templates/MUPolls/vote/display.json.tpl
modules/MUPolls/templates/vote/display.tpl: config/templates/MUPolls/vote/display.tpl
modules/MUPolls/templates/admin/header.tpl: config/templates/MUPolls/admin/header.tpl
modules/MUPolls/templates/admin/footer.tpl: config/templates/MUPolls/admin/footer.tpl
modules/MUPolls/templates/user/header.tpl: config/templates/MUPolls/user/header.tpl
modules/MUPolls/templates/user/footer.tpl: config/templates/MUPolls/user/footer.tpl
modules/MUPolls/templates/admin/inlineRedirectHandler.tpl: config/templates/MUPolls/admin/inlineRedirectHandler.tpl
modules/MUPolls/templates/user/inlineRedirectHandler.tpl: config/templates/MUPolls/user/inlineRedirectHandler.tpl
modules/MUPolls/templates/option/edit.tpl: config/templates/MUPolls/option/edit.tpl
modules/MUPolls/templates/option/inlineRedirectHandler.tpl: config/templates/MUPolls/option/inlineRedirectHandler.tpl
modules/MUPolls/templates/poll/edit.tpl: config/templates/MUPolls/poll/edit.tpl
modules/MUPolls/templates/poll/inlineRedirectHandler.tpl: config/templates/MUPolls/poll/inlineRedirectHandler.tpl
modules/MUPolls/templates/vote/edit.tpl: config/templates/MUPolls/vote/edit.tpl
modules/MUPolls/templates/vote/inlineRedirectHandler.tpl: config/templates/MUPolls/vote/inlineRedirectHandler.tpl
modules/MUPolls/templates/helper/includeStandardFieldsDisplay.tpl: config/templates/MUPolls/helper/includeStandardFieldsDisplay.tpl
modules/MUPolls/templates/helper/includeStandardFieldsEdit.tpl: config/templates/MUPolls/helper/includeStandardFieldsEdit.tpl
modules/MUPolls/templates/admin/config.tpl: config/templates/MUPolls/admin/config.tpl
modules/MUPolls/templates/includePdfHeader.tpl: config/templates/MUPolls/includePdfHeader.tpl
