<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\PollsModule;

use MU\PollsModule\Base\AbstractPollsModuleInstaller;

/**
 * Installer implementation class.
 */
class PollsModuleInstaller extends AbstractPollsModuleInstaller
{
    // feel free to extend the installer here
}
