<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\PollsModule\Validator\Constraints;

use MU\PollsModule\Validator\Constraints\Base\AbstractListEntry;

/**
 * List entry validation constraint.
 *
 * @Annotation
 */
class ListEntry extends AbstractListEntry
{
    // here you can customise the constraint
}
