<?php
/**
 * Polls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\PollsModule\Entity\Factory\Base;

use MU\PollsModule\Entity\OptionEntity;
use MU\PollsModule\Entity\PollEntity;
use MU\PollsModule\Entity\VoteEntity;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * Initialises a given option instance.
     *
     * @param OptionEntity $entity The newly created entity instance
     *
     * @return OptionEntity The updated entity instance
     */
    public function initOption(OptionEntity $entity)
    {
        return $entity;
    }

    /**
     * Initialises a given poll instance.
     *
     * @param PollEntity $entity The newly created entity instance
     *
     * @return PollEntity The updated entity instance
     */
    public function initPoll(PollEntity $entity)
    {
        return $entity;
    }

    /**
     * Initialises a given vote instance.
     *
     * @param VoteEntity $entity The newly created entity instance
     *
     * @return VoteEntity The updated entity instance
     */
    public function initVote(VoteEntity $entity)
    {
        return $entity;
    }

}
