<?php
/**
 * MUPolls.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUPolls
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

include_once 'Needles/Base/Abstractoption_info.php';

/**
 * MUPolls option needle information.
 *
 * @param none
 *
 * @return string with short usage description
 */
function MUPolls_needleapi_option_info()
{
    return MUPolls_needleapi_option_baseInfo();
}
